openapi: 3.0.3
info:
  title: BSCI to Vanderlande - HU Master Interface
  description: |-
    This is a HU Master API based on the OpenAPI 3.0 specification. 
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://vanderlande_tbd.com/api/v1
tags:
  - name: HU Master
    description: API to post HU Master data from BSC EWM to Vanderlande
paths:
  /bsc/hu_master:
    post:
      tags:
        - HU Master
      summary: Post HU Master data to Vanderlande system
      description: This API is hosted on Vanderlande server and called by BSC to deliver the HU Master data
      operationId: postHUMaster
      requestBody:
        description: Post HU Master data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HUMasterMessageRequest'
                                
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HUMasterMessageResponse'          

        '400':
          description: Invalid input
        '422':
          description: Validation exception
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HUMasterMessageResponse'
      security:
        - OAuth2:
            - write
            - read
            


components:
  schemas:
    HUMasterMessageRequest:
      type: object
      properties:
        HUMasterMessageRequest:
          type: object
          properties:
            messageHeader:              
              $ref: '#/components/schemas/messageHeader'
            handlingunit:
              oneOf:
               - $ref: '#/components/schemas/handlingunit_new_change'
               - $ref: '#/components/schemas/handlingunit_cancel'              

    messageHeader: 
          type: object
          required:
            - msgId
            - msgType
            - transCode
            - sender
            - receiver
            - dateTimeSent
          properties: 
            msgId: 
              type: string
              minLength: 1
              maxLength: 20
              example: '27651234'
              description: Unique ID of the message. Incremental number for now. Can be up to 20 characters, so no need to recycle. May change to alpha-numeric in future
            msgType: 
              type: string
              minLength: 8
              maxLength: 8
              enum: [HUMaster]
              example: HUMaster
              description: Describes the type of interface (always the same for Vanderlande)
            transCode: 
              type: string
              minLength: 3
              maxLength: 6
              enum:
                - NEW
                - CHANGE
                - CANCEL
              example: NEW
              description: This field describes the type of interface to the conveyor. NEW- new box being announced to the MFC. CHANGE- update of a box that was previously announced. CANCEL- all destinations for this box can be cancelled as the box will not be created or has been removed from the conveyor.*handlingunit Schema should change based on the transcode value. For NEW and CHANGE transcodes, handlingunit_new_change' schema should be used. For CANCEL transcode, 'handlingunit_cancel' schema should be used.
            sender: 
              type: string
              maxLength: 18
              enum: [EWM_KER1]
              example: EWM_KER1
              description: Indicates the system that is sending the information. Constant Value will be sent - 'EWM_KER1'
            receiver: 
              type: string
              maxLength: 18
              enum: [Vanderlande_KER1]
              example: Vanderlande_KER1
              description: Indicates the system that is supposed to receive the information. Canstat value will be sent - 'Vanderlande_KER1'
            dateTimeSent: 
              type: string
              format: date-time
              example: 2002-05-30T09:30:10Z
              description: Message creation time in UTC. The format is YYYY-MM-DDThh:mm:ssZ. 
       
    handlingunit_new_change: 
      type: object
      required:
        - HUId
        - dispatchDate
        - shipToCountry
        - routeCode
        - carrier       
        - PackSizeBoxOfBoxes      
        - delivery
      properties: 
        HUId:         
          type: string
          maxLength: 20          
          example: '700001057835'
          description: Handling Unit number. This is similar to the number of the box (18-digits) and will also be reflected in the HU-barcode in SSCC-format
        VAS: 
          type: object
          required:
            - Activity
          properties: 
            Activity: 
              type: array
              minItems: 1
              maxItems: 20
              items: 
                type: string
              example: ["LLI", "DFU"]
          description: This section indicates the type of value added service(s) that is/are needed. In the interface, there can be multiple activities within the <VAS>-section.
        pickVerification: 
          type: string
          enum:
            - 'true'
            - 'false'
          description: Indicates whether the box has to go to the pick verification. Possible values are true or false.
          example: 'true'
        packLane: 
          type: string
          minLength: 1
          maxLength: 4
          example: MHU
          description: The packline field indicates the type of packing needed for the box. There can be only 1 type of packing in this field. Route to MHU for Delivery Group / Complete delivery Indicator deliveries. MANUALPACK and MHU will be same conveyor area mapped under Vision.
        delivery: 
          type: string
          minLength: 1
          maxLength: 35
          example: '4312500640'
          description: Outbound Delivery Number
        dispatchDate: 
          type: string
          format: date-time
          example: 2002-05-30T09:30:10Z
          description: TimesStamp in UTC when the delivery was released for the picking process (in EWM this will be the Latest Start Date &Time) 
        shipToCountry: 
          type: string
          minLength: 2
          maxLength: 3
          example: DE
          description: Country to which the HU will be shipped
        routeCode: 
          type: string
          minLength: 1
          maxLength: 10
          example: ZTNTEC
          description: The route that SAP has assigned to the HU
        carrier: 
          type: string
          example: DHL parcel
          description: Carrier Partner in Delivery
        serviceType: 
          type: string
          example: Pre8
          minLength: 0
          maxLength: 10
          description: The type of service that the carrier is requested to provide (for example delivery before 9am, deliver next day, delivery at the department etc.). Not required by Vanderlande as of now.
        cutoffDate: 
          type: string
          format: date-time
          example: 2002-05-30T09:30:10Z
          description: Indicates the time in UTC when the box has to be handed over to the carrier. The format is YYYY-MM-DDThh:mm:ssZ. 
        boxLength: 
          type: string
          maxLength: 17
          example: '255'
          description: Inner length of the box (mm)
        boxWidth: 
          type: string
          maxLength: 17
          example: '234'
          description: Inner width of the box (mm)
        boxHeight: 
          type: string
          maxLength: 17
          example: '47'
          description: Inner height of the box (mm)
        PackSizeBoxOfBoxes: 
          type: string
          maxLength: 20
          example: 1 of 1
          description: Indicates the number of the box within the delivery
        totalBoxWeight: 
          type: string
          maxLength: 40
          example: '8.99'
          description: Estimated total weight of the box and the products (g)
        orderLines: 
          type: array
          minItems: 1
          maxItems: 999
          items: 
            type: object
            required:
              - pickArea
            properties: 
              pickArea: 
                type: string
                minLength: 1
                maxLength: 4
                example: P03
                description: Order Lines-Pick Area where picking is to be done. In EWM, pick area is the activity area for the open lower level WOs . 
              numberOfLines: 
                type: string
                example: '3'
                description: Order Lines - Number of Lines. In EWM, count of all warehouse tasks in the open lower level WOS 
              quantityOrdered: 
                type: string
                example: '6'
                description: Order Lines- Quantity to be picked. In EWM, count BUOM quantity of warehouse tasks in the open lower level WOS 

    handlingunit_cancel: 
      type: object             
      required:
        - HUId
      properties: 
        HUId:         
          type: string
          maxLength: 20          
          example: '700001057835'
          description: Handling Unit number. This is similar to the number of the box (18-digits) and will also be reflected in the HU-barcode in SSCC-format

    HUMasterMessageResponse:
      type: object
      properties:
        HUMasterMessageResponse:
          type: object
          properties:
            messageHeader:              
              $ref: '#/components/schemas/responseMessageHeader'
            responseMessage:
                $ref: '#/components/schemas/responseMessage' 

    responseMessageHeader: 
          type: object
          required:
            - msgId
            - msgType
            - transCode
            - sender
            - receiver
            - dateTimeReceived
          properties: 
            msgId: 
              type: number
              minimum: 1
              maximum: 99999999999999999999
              example: 27651234
              description: Unique number of the message that was sent to Vanderlande. 
            msgType: 
              type: string
              minLength: 1
              maxLength: 20
              enum: [HUMaster]
              example: HUMaster
              description: Describes the type of interface (always the same for Vanderlande)
            transCode: 
              type: string
              enum:
                - NEW
                - CHANGE
                - CANCEL
              example: NEW
              description: Send back the same transcode that was sent to Vanderlande
            sender: 
              type: string
              enum: [Vanderlande_KER1]
              example: Vanderlande_KER1
              description: Indicates the system that is sending the information
            receiver: 
              type: string
              enum: [EWM_KER1]
              example: EWM_KER1
              description: Indicates the system that is supposed to receive the information
            dateTimeReceived: 
              type: string
              format: date-time
              example: 2002-05-30T09:30:10Z
              description: Indicates when the message was recieved by Vanderlande in UTC. The format is YYYY-MM-DDThh:mm:ssZ. 

        
    responseMessage:
      type: object
      properties:
        message:
          type: string
          maxLength: 100
          description: response message. Mentions success or any validation failure reason along with the field name e.g. Error- Validation failed- dateTimeSent
          example: Success - Accepted or Error- Validation failed- dateTimeSent, PackSizeBoxOfBoxes

  securitySchemes:
    api_key:
      type: apiKey
      name: api_key
      in: header

    BasicAuth:
      type: http
      scheme: basic

    BearerAuth:
      type: http
      scheme: bearer

    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key

    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://example.com/oauth/authorize
          tokenUrl: https://example.com/oauth/token
          scopes:
            read: Grants read access
            write: Grants write access
            admin: Grants access to admin operations      
