openapi: 3.0.3
info:
  title: BSCI to Vanderlande - HU Master Interface
  description: |-
    This is a HU Master API based on the OpenAPI 3.0 specification. 
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://vanderlande_tbd.com/api/v1
tags:
  - name: HU Master
    description: API to post HU Master data from BSC EWM to Vanderlande
paths:
  /bsc/HUMaster:
    post:
      tags:
        - HU Master
      summary: Post HU Master data to Vanderlande system
      description: This API is hosted on Vanderlande server and called by BSC to deliver the HU Master data
      operationId: postHUMaster
      requestBody:
        description: Post HU Master data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HUMasterMessageRequest'
                                
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/handlingunit_cancel'          

        '400':
          description: Invalid input
        '422':
          description: Validation exception
      security:
        - petstore_auth:
            - write:pets
            - read:pets
            


components:
  schemas:
    HUMasterMessageRequest:
      type: object
      properties:
        HUMasterMessageRequest:
          type: object
          properties:
            messageHeader:              
              $ref: '#/components/schemas/messageHeader'
            handlingunit:
               $ref: '#/components/schemas/handlingunit_new_change'              

    messageHeader: 
          type: object
          required:
            - msgId
            - msgType
            - transCode
            - sender
            - receiver
            - dateTimeSent
          properties: 
            msgId: 
              type: number
              minimum: 1
              maximum: 99999999999999999999
              example: 27651234
              description: Unique number of the message. Incremental number. Can be up to 20 digits, so no need to recycle.
            msgType: 
              type: string
              minLength: 1
              maxLength: 20
              enum: [HUMaster]
              example: HUMaster
              description: Describes the type of interface (always the same for Vanderlande)
            transCode: 
              type: string
              enum:
                - NEW
                - CHANGE
                - CANCEL
              example: NEW
              description: This field describes the type of interface to the conveyor - NEW- new box being announced to the MFC CHANGE- update of a box that was previously announced CANCEL- all destinations for this box can be cancelled as the box will not be created or has been removed from the conveyor.              *handlingunit Schema should change based on the transcode value. For NEW and CHANGE transcodes, handlingunit_new_change' schema should be used. For CANCEL transcode, 'handlingunit_cancel' schema should be used.
            sender: 
              type: string
              enum: [EWM_KER1]
              example: EWM_KER1
              description: Indicates the system that is sending the information
            receiver: 
              type: string
              enum: [Vanderlande_KER1]
              example: Vanderlande_KER1
              description: Indicates the system that is supposed to receive the information
            dateTimeSent: 
              type: string
              format: date-time
              example: 2021-12-20T14:48:58.214+01:00
              description: Indicates when the interface was sent. The format is YYYY-MM-DDThh:mm:ss-hh:mm . The “+01:00” in example indicates timezone offset i.e. means one hour ahead of UTC (Coordinated Universal Time) in this example. https://help.sap.com/docs/business-network-for-supply-chain/cxml-solutions/date-and-time-format
       
    handlingunit_new_change: 
      type: object
      required:
        - HUId
        - dispatchDate
        - shipToCountry
        - routeCode
        - carrier
        - serviceType
        - Pack-SizeBoxOfBoxes
        - totalBoxWeight
        - orderLines
      properties: 
        HUId:         
          oneOf:
            - type: string
            - type: integer
          maxLength: 18
          maximum: 999999999999999999
          example: 700001057835
          description: Handling Unit number. This is similar to the number of the box (18-digits) and will also be reflected in the HU-barcode in SSCC-format
        VAS: 
          type: object
          required:
            - Activity
          properties: 
            Activity: 
              type: array
              minItems: 1
              maxItems: 20
              items: 
                type: string
              example: ["LLI", "DFU"]
          description: This section indicates the type of value added service(s) that is/are needed. In the interface, there can be multiple activities within the <VAS>-section.
        pickVerification: 
          type: boolean
          description: Indicates whether the box has to go to the pick verification
        packLane: 
          type: string
          minLength: 1
          maxLength: 4
          example: MHU
          description: The packline field indicates the type of packing needed for the box. There can be only 1 type of packing in this field
        delivery: 
          type: string
          minLength: 1
          maxLength: 35
          example: 4312500640
          description: Delivery Number
        dispatchDate: 
          type: string
          format: date-time
          example: 2021-12-20T14:48:58.214+01:00
          description: TimesStamp when the delivery was released for the picking process (in EWM this will be the Latest Start Date &Time) The format is YYYY-MM-DDThh:mm:ss-hh:mm . The “+01:00” in example indicates timezone offset i.e. means one hour ahead of UTC (Coordinated Universal Time) in this example. https://help.sap.com/docs/business-network-for-supply-chain/cxml-solutions/date-and-time-format
        shipToCountry: 
          type: string
          minLength: 2
          maxLength: 3
          example: DE
          description: Country to which the HU will be shipped
        routeCode: 
          type: string
          minLength: 1
          maxLength: 10
          example: ZTNTEC
          description: The route that SAP has assigned to the HU
        carrier: 
          type: string
          example: DHL parcel
          description: The carrier that will be transporting the box
        serviceType: 
          type: string
          example: Pre8
          minLength: 1
          maxLength: 10
          description: The type of service that the carrier is requested to provide (for example delivery before 9am, deliver next day, delivery at the department etc.)
        cutOff: 
          type: string
          example: 2021-12-20T18:48:00
        boxLength: 
          type: number
          example: 255
        boxWidth: 
          type: number
          example: 234
        boxHeight: 
          type: number
          example: 47
        Pack-SizeBoxOfBoxes: 
          type: string
          example: 1 of 1
        totalBoxWeight: 
          type: number
          example: 3000
        orderLines: 
          type: array
          items: 
            type: object
            properties: 
              pickArea: 
                type: string
                example: P03
              numberOfLines: 
                type: number
                example: 3
              quantityOrdered: 
                type: number
                example: 6

    handlingunit_cancel: 
      type: object             
      required:
        - HUId
      properties: 
        HUId: 
          type: number
          example: 700001057835
  securitySchemes:
    petstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://petstore3.swagger.io/oauth/authorize
          scopes:
            write:pets: modify pets in your account
            read:pets: read your pets
    api_key:
      type: apiKey
      name: api_key
      in: header
